# Generated by Django 6.0.2 on 2026-02-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(verbose_name='Opis')),
                ('short_description', models.CharField(max_length=300, verbose_name='Kratak opis')),
                ('technologies', models.CharField(max_length=200, verbose_name='Tehnologije')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Glavna slika')),
                ('screenshot_1', models.ImageField(blank=True, null=True, upload_to='projects/screenshots/', verbose_name='Screenshot 1')),
                ('screenshot_2', models.ImageField(blank=True, null=True, upload_to='projects/screenshots/', verbose_name='Screenshot 2')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub link')),
                ('live_url', models.URLField(blank=True, verbose_name='Live demo link')),
                ('featured', models.BooleanField(default=False, verbose_name='Istaknuti projekt')),
                ('completed_date', models.DateField(verbose_name='Datum završetka')),
                ('order', models.IntegerField(default=0, verbose_name='Redosled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projekat',
                'verbose_name_plural': 'Projekti',
                'ordering': ['order', '-completed_date'],
            },
        ),
    ]
