# Generated by Django 6.0.2 on 2026-02-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Broj pregleda'),
        ),
    ]
